spring:
  datasource:
    # URL k?t n?i m?c ??nh c?a PostgreSQL
    url: jdbc:postgresql://localhost:5432/booking_platform_db
    username: postgres      # Tài kho?n m?c ??nh th??ng là 'postgres'
    password: 123456      # Thay b?ng m?t kh?u b?n ?ã cài ??t
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Ch? ??nh cho Hibernate bi?t ?ây là PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
